/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica;

import forms.especilidades.FrmEspecialidades;
import forms.obrasocial.FrmObraSocial;
import forms.pacientes.FrmPacientes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import miselaneos.Fecha;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.imagenes;

public class FrmSistema extends javax.swing.JFrame {

    // Declaración de objetos estáticos para acceder desde cualquier parte del proyecto
    public static Iconos iconos = new Iconos();
    public static imagenes imgs = new imagenes();
    public static Fecha Fe = new Fecha();
    private GUI gui;

    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        gui = new GUI();
    }

    // Método para cargar la ventana de Obra Social
    private void loadObraSocial() {
        gui.loadObraSocial(FrmObraSocial.id, true);
    }

    // Método para cargar la ventana de Pacientes
    private void loadPacientes() {
        gui.loadPacientes(FrmPacientes.id, true);
    }

    // Método para cargar la ventana de Especialidades
    private void loadEspecialidades() {
        gui.loadEspecialidades(FrmEspecialidades.id, true);
    }

    /**
     * Método para salir del sistema
     */
    private void salirSistema() {
        if (JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema por Completo.", "ATENCIÓN!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeskTopSis = new miselaneos.JDeskTopSis();
        btnNota = new javax.swing.JButton();
        jToolBarButtons = new javax.swing.JToolBar();
        btnObraSocial = new botones.BtnObraSocial();
        btnClient = new botones.BtnClient();
        btnExit = new botones.BtnExit();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivos = new javax.swing.JMenu();
        jMenuIObraSocial = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Clinica");
        setIconImage(iconos.getSys(16).getImage());

        jDeskTopSis.setPreferredSize(new java.awt.Dimension(1024, 800));

        btnNota.setText("Nota");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });
        jDeskTopSis.add(btnNota);
        btnNota.setBounds(10, 10, 68, 25);

        getContentPane().add(jDeskTopSis, java.awt.BorderLayout.CENTER);

        jToolBarButtons.setRollover(true);

        btnObraSocial.setText("");
        btnObraSocial.setFocusable(false);
        btnObraSocial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObraSocial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObraSocialActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnObraSocial);

        btnClient.setText("");
        btnClient.setFocusable(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnClient);

        btnExit.setText("");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnExit);

        getContentPane().add(jToolBarButtons, java.awt.BorderLayout.NORTH);

        jMenuArchivos.setText("Archivo");
        jMenuArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArchivosActionPerformed(evt);
            }
        });

        jMenuIObraSocial.setIcon(iconos.getObraSocial(32)
        );
        jMenuIObraSocial.setText("Obra Social");
        jMenuIObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIObraSocialActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuIObraSocial);

        jMenuPacientes.setIcon(iconos.getClient(32));
        jMenuPacientes.setText("Pacientes");
        jMenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPacientesActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuPacientes);

        jMenuItem1.setIcon(iconos.getEspecialidades(32)
        );
        jMenuItem1.setText("Especialidades");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuItem1);

        jMenuBar.add(jMenuArchivos);

        jMenuSalir.setText("Salir");

        jMenuItem3.setIcon(iconos.getExit(16));
        jMenuItem3.setText("Salir Del Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItem3);

        jMenuBar.add(jMenuSalir);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
